version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./data/www:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d
    depends_on:
      - php
  
  php:
    image: php:7.4-fpm
    volumes:
      - ./data/www:/var/www
